### ISSUE TITLE
components文件没有

### ISSUE THREAD

**Issue by ioslide** [panmenglin/mp-photo-album#4]
老板，components文件没有

**Comment by panmenglin** [comment]
> 老板，components文件没有

引入 npm 组件直接安装构建即可

`npm install --save --production mp-photo-album`

安装之后在微信开发者工具菜单中选择 `工具-构建npm`
会在文件夹 miniprogram_npm 下生成对应文件，即可使用 usingComponents 正常引用，
不会有 components 文件生成
